### ISSUE TITLE
[Task] Tab content in the Topology renders with no height

### ISSUE THREAD

**Issue by aptmac** [cryostatio/cryostat-openshift-console-plugin#120]
Ran into another styling issue. This time it's the tab-content section in the Topology page, the plugin has it with a height of 0 so none of the details end up showing. I have screenshots below highlighting the same component to illustrate:

Expected:

![expected](https://github.com/user-attachments/assets/df9e99c0-153b-4224-ab60-fdd29d4d08d5)

Actual:

![actual](https://github.com/user-attachments/assets/0e693d7a-3685-49df-9389-ddc2bee810cb)

**Comment by aptmac** [comment]
Or, I wonder if there is something going on instead that's making this have no height.

My Chrome console is displaying a ton of: 
`app.jsx:580 unhandled error: Uncaught Error: GraphElement with ID 'cryostat-target-topology-graph' has no controller. Error: GraphElement with ID 'cryostat-target-topology-graph' has no controller.`

**Comment by andrewazores** [comment]
Hmm. The Topology view is quite complex and also does some caching to localstorage to persist the graph layout and things. I wonder if maybe there's a localstorage key conflict with the console or something like that.

Here is where that ID is defined and used:

https://github.com/cryostatio/cryostat-web/blob/6f0b1ac73533995fb6c0b92cb3e3d3bc7992cd54/src/app/Topology/Shared/utils.tsx#L36

https://github.com/cryostatio/cryostat-web/blob/6f0b1ac73533995fb6c0b92cb3e3d3bc7992cd54/src/app/Topology/GraphView/TopologyGraphView.tsx#L174

I think this is supposed to initialize the missing controller:

https://github.com/cryostatio/cryostat-web/blob/6f0b1ac73533995fb6c0b92cb3e3d3bc7992cd54/src/app/Topology/GraphView/TopologyGraphView.tsx#L192

**Comment by andrewazores** [comment]
@tthvo you wouldn't happen to remember the details here and have any ideas, would you? :-)

**Comment by aptmac** [comment]
On further review, it looks like these are two separate issues, I just happened to find the console logs when trying to figure out the stylesheet issues.

For some reason there's a element here that fills most of the component and shifts all the content below the screen:

![before](https://github.com/user-attachments/assets/3b739493-ceae-4fa5-bcb0-d4b1ef6ce165)

And if I just remove that component then the details are visible again:

![hack](https://github.com/user-attachments/assets/8a137c0d-be98-4e5a-b082-20cfa89e2cb7)

**Comment by tthvo** [comment]
> For some reason there's a element here that fills most of the component and shifts all the content below the screen:

Hey @andrewazores @aptmac, I pretty much arrived at the same conclusion after spectating the panel :D It does seems like the OpenShift console has an css override for `pf-v5-c-drawer__body` that set `height: 100%` (which will break the panel styling). See below on the top-right.

![Image](https://github.com/user-attachments/assets/d6efb80f-22dc-4a72-8e8c-9bafca31e6e9)

I think we can fix this by override that again to unset. Something this:

```css
/** 
 * Reset the height property of pf-v5-c-drawer__body (overrided by OpenShift console to 100%) 
 * The topology detail panel relies on flex box property to make the content body fill vertical space and allow scrolling if overflow.
 * Setting height to 100% breaks the view since the header takes all vertical space instead, resulting no space for body.
 */
.topology__main-container {
    .pf-v5-c-drawer__body {
        height: unset;
    }
}
```

I have an image here if you'd like to try: `quay.io/thvo/cryostat-openshift-console-plugin:latest` (this patches the `src/openshift/styles/plugin.css`). It should look like below

![Image](https://github.com/user-attachments/assets/01096c8d-7b1c-41f6-839a-c4da0394db72)
